build-job:
  stage: build
  script:
    - echo "Building..."
    - npm i --max-old-space-size=400
    - npm run build --max-old-space-size=400

test-job:
  stage: test
  script:
    - echo "Testing..."
    - echo "TODO..."

deploy-dev:
  stage: deploy
  script:
    - npm i --max-old-space-size=400
    - npm run build --max-old-space-size=400
    - cp -a ./build/. /home/defiv2/frontend
