build-job:
  stage: build
  script:
    - echo "Building..."
    - npm i
    - npm run build

test-job:
  stage: test
  script:
    - echo "Testing..."
    - echo "TODO..."

deploy-dev:
  stage: deploy
  script:
    - npm i
    - npm run build
    - rm -r /home/defi/frontend/*
    - cp -r build/* /home/defi/frontend/
  only:
    - master
    - develop
